project_id = "zydczhczilqfjmcqjktt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.analyze-recording]
verify_jwt = false

[functions.analyze-recording.node_compat]
enabled = true

[functions.execute-automation]
verify_jwt = false

[functions.manus-proxy]
verify_jwt = false

[functions.process-recording]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-adjust-quota]
verify_jwt = false

[functions.admin-platform-stats]
verify_jwt = false
